apiVersion: apps/v1
kind: Deployment

metadata:
  name: url-monitor-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: url-monitor

  template:
    metadata:
      labels:
        app: url-monitor

    spec:
      containers:
      - name: url-monitor

        image: cloud-url-monitor:latest

        imagePullPolicy: Never

        ports:
        - containerPort: 8000