apiVersion: v1
kind: Service

metadata:
  name: cloud-url-monitor-service

spec:
  selector:
    app: cloud-url-monitor

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30008

  type: NodePort
